### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by K2AAE** [HR/github-clone#6]
I just tried to clone adafruit:
>ghclone https://github.com/adafruit -t mytoken
Invalid GitHub URI

Am I doing something wrong?

**Comment by HR** [comment]
@K2AAE https://github.com/adafruit is not a repo so you cannot clone it.

Also the `-t` argument requires your real GitHub OAuth token and is only required for very large or private repos (see https://github.com/HR/github-clone#rate-limit)

Here are some usage examples:
```
$ ghclone https://github.com/HR/Crypter/tree/master/app
$ ghclone https://github.com/HR/Crypter/tree/dev/app
$ ghclone https://github.com/HR/Crypter/tree/v3.1.0/build
$ ghclone https://github.com/HR/Crypter/tree/cbee54dd720bb8aaa3a2111fcec667ca5f700510/build
```
