### ISSUE TITLE
raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 503 Server Error: Server Temporarily Unavailable for url: http://grcm39.rest.ensembl.org/variation/Mus_musculus?pops=1

### ISSUE THREAD

**Issue by guoyanyunyancaizi** [HR/github-clone#7]
Hi,
    I running a script,  it presents this problem:

File "E:\python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Server Temporarily Unavailable for url: http://grcm39.rest.ensembl.org/variation/Mus_musculus?pops=1

OS: win10, x64.
Thanks

**Comment by HR** [comment]
Hi @guoyanyunyancaizi,

It looks like you are passing a non-GitHub url to ghclone.

Github clone only works for GitHub repositories as it uses the GitHub API to download the sub-directories.

Please refer to the [README](https://github.com/HR/github-clone/blob/master/README.md) for more info.
