### ISSUE TITLE
Failed to fetch metadata

### ISSUE THREAD

**Issue by zulalnb** [HR/github-clone#8]
I get error subdirectories of nothing but [realtime-colors subdirectory](https://github.com/Kodluyoruz/taskforce/tree/react-patika/react-patika/realtime/realtime-colors)

`Failed to fetch metadata realtime-colors`

**Comment by teebu** [comment]
how did you solve this?

**Comment by Xelbayria** [comment]
Have you solve the problem? I am facing the same problem `Failed to fetch metadata for <sub-directory>`
